README.md
examples/BUILD
examples/hello-grpc/BUILD
examples/hello-grpc/deployment.yaml
k8s/object.bzl

This contains just enough to define a k8s_object rule that effectively passes through the input object.
Subsequent changes will expand the surface of this to support more meaningful operations.

Add the k8s_object rule.

---

README.md
WORKSPACE
examples/hello-grpc/BUILD
k8s/k8s.bzl
k8s/with-defaults.bzl

This adds the next piece of functionality: `k8s_defaults`.
This is built upon https://github.com/bazelbuild/rules_k8s/pull/2, and I'll continue to rebase it as that moves along.

Add aliasing

---

README.md
examples/hello-grpc/cc/server/BUILD
k8s/object.bzl
k8s/resolver.py
k8s/resolver_test.py

When the `images={}` attribute is specified resolution will publish the collection of images, and substitute the exact digest of the published image as part of resolution (avoids race condition).

Add support for the `images={}` attribute.

---

k8s/object.bzl

The `set` constructor in Skylark is deprecated and will be removed soon in favor of `depset` Furthermore, depsets will become non-iterable in the future, the recommended way for deduplicating lists is by using dicts: `{k: None for k in iterable}.keys()`.

Remove deprecated set constructor

---

k8s/object.bzl

This removes the bug not allowing k8s_object() to work on images from docker_build() targets with a legacy layer.
I saw your pending change to move from .short_path and this will need updating as well.
And good job with rules_k8s! :)
//David, from Cinnober

Bugfix: Extracts short_path from tarball-File

---

examples/hellogrpc/e2e-test.sh
k8s/BUILD
k8s/create.sh.tpl
k8s/delete.sh.tpl
k8s/describe.sh.tpl
k8s/object.bzl
k8s/resolve.sh.tpl

This hinders two things:
1. Separate `bazel build` and running via `bazel-bin/...` (vs. `bazel run`)
1. Embedding these scripts into other actions.
This also changes the tool references from `.par` to the `py_binary` directly as this should improve portability to Windows.
Fixes: https://github.com/bazelbuild/rules_k8s/issues/26

Stop using .short_path to reference stuff in actions.

---

README.md
WORKSPACE
examples/hellogrpc/BUILD
examples/hellogrpc/service.yaml
k8s/BUILD
k8s/objects.bzl
k8s/resolve-all.sh.tpl

`k8s_objects` takes a list of K8s objects across which to take certain actions.
`k8s_objects` also supports nesting, so a `k8s_objects` can take another `k8s_objects`.
Fixes: https://github.com/bazelbuild/rules_k8s/issues/46

This change adds preliminary support for k8s_objects.

---

README.md
WORKSPACE
examples/hellogrpc/cc/server/BUILD
examples/hellogrpc/deployment.jsonnet
examples/hellogrpc/deployment.yaml
examples/hellogrpc/go/server/BUILD
examples/hellogrpc/java/server/BUILD
examples/hellogrpc/py/server/BUILD
examples/hellohttp/deployment.jsonnet
examples/hellohttp/deployment.yaml
examples/hellohttp/go/BUILD
examples/hellohttp/java/BUILD
k8s/object.bzl
k8s/resolve.sh.tpl
k8s/resolver.py
k8s/resolver_test.py
k8s/with-defaults.bzl

Fixes: https://github.com/bazelbuild/rules_k8s/issues/47

Allow k8s_object to chroot image references

---

.ci/rules_k8s.json

This is blocking the addition of several Python samples, including the http one and the TODO controller.
The cause is tracked by [this](https://github.com/bazelbuild/rules_python/issues/17) and [this](https://github.com/google/subpar/issues/38) issue.
Currently Bazel CI doesn't provide very meaningful coverage, most of it happens via Travis and example e2e tests.

This disables OSX validation on the Bazel CI setup.

---

.travis.yml
WORKSPACE
examples/todocontroller/BUILD
examples/todocontroller/deployment.yaml
examples/todocontroller/e2e-test.sh
examples/todocontroller/example.yaml
examples/todocontroller/py/BUILD
examples/todocontroller/py/controller.py
examples/todocontroller/py/edit.sh
examples/todocontroller/py/requirements.txt
examples/todocontroller/todo.yaml

This has a handful of components:
- a "TODO" Custom Resource Definition (CRD),
- a "TODO" example instance, and
- a Custom Controller that watches for "TODOs" not marked "done" and completes them with a comment.
This also adds a little e2e test that:
- Creates the CRD/Controller and starter TODO
- Checks the note on the TODO
- Updates the Controller (waits) and then the TODO (waits)
- Checks the note on the TODO has changed appropriately
- Repeat edit/check
- Teardown
Fixes: https://github.com/bazelbuild/rules_k8s/issues/30

Add a simple Kubernetes custom controller/resource example.

---

examples/hellohttp/BUILD
examples/hellohttp/deployment.jsonnet
examples/hellohttp/deployment.yaml
examples/hellohttp/go/BUILD
examples/hellohttp/java/BUILD
examples/hellohttp/py/BUILD
k8s/object.bzl
k8s/resolver.py
k8s/resolver_test.py

Removes some of the friction from: https://github.com/bazelbuild/rules_k8s/issues/68
Fixes: https://github.com/bazelbuild/rules_k8s/issues/69

Address a few pieces of feedback from @ensonic

---

README.md
k8s/apply.sh.tpl
k8s/create.sh.tpl
k8s/delete.sh.tpl
k8s/describe.sh.tpl
k8s/object.bzl
k8s/replace.sh.tpl

* mentions dependencies in the docs
* make the namespace attribute on k8s_object optional

Two small improvements

---

README.md
k8s/apply.sh.tpl
k8s/create.sh.tpl
k8s/delete.sh.tpl
k8s/describe.sh.tpl
k8s/object.bzl
k8s/replace.sh.tpl

Merge #84 into master

---

k8s/object.bzl

This allows namespace to be solely specified in the config file.
#81

Remove default value for namespace

---

README.md
k8s/object.bzl

The custom resolver mattmoor@ mentioned seems to be a very workable solution for endpoint resolving (#88). I've made a PoC implementation in http://shortn/_0SyJs3BlK7 (Google-internal link) that uses a custom resolver to resolve endpoint versions after Docker digests were resolved. Could you PTAL?

Make resolver a public property

---

k8s/object.bzl

This PR is to propose a fix to #77

Expand make vars for cluster name

---

k8s/resolver.py

Related to: https://github.com/google/containerregistry/issues/56

Don't dump a stack trace when we hit errors publishing images.

---

examples/todocontroller/deployment.yaml
k8s/BUILD
k8s/resolver.py
k8s/reverser.py

Fixes: https://github.com/bazelbuild/rules_k8s/issues/116

Properly support multi-document yaml files.

---

WORKSPACE
k8s/object.bzl

The file was renamed in https://github.com/bazelbuild/rules_docker/pull/279.

Fix file reference to rules_docker

---

k8s/resolver.py

The current message:
```
The following image references were not found: [eu.gcr.io/robco-rodrigoq/move-endpoint:latest]
```
suggests to the untrained eye that they should check that image has not
been found on the container registry, as the user may not know that the
resolver is replacing image references inside the YAML file.
This commit changes the message to:
```
ERROR: The following image references were not found in '/your/bazel/cache/dir/execroot/__main__bazel-out/k8-opt/bin/your/package/path/k8s.runfiles/__main__/your/package/path/deployment.yaml':
eu.gcr.io/robco-rodrigoq/move-endpoint:latest
```
which is very long but hopefully clearer, as the user can look at that
file to work out why the image reference is not found.

Improve "not found" error message

---

k8s/resolver.py

The current message:
```
The following image references were not found: [eu.gcr.io/robco-rodrigoq/move-endpoint:latest]
```
suggests to the untrained eye that they should check that image has not
been found on the container registry, as the user may not know that the
resolver is replacing image references inside the YAML file.
This commit changes the message to:
```
ERROR: The following image references were not found in '/your/bazel/cache/dir/execroot/__main__bazel-out/k8-opt/bin/your/package/path/k8s.runfiles/__main__/your/package/path/deployment.yaml':
eu.gcr.io/robco-rodrigoq/move-endpoint:latest
```
which is very long but hopefully clearer, as the user can look at that
file to work out why the image reference is not found.

Improve "not found" error message (#121)

---

k8s/object.bzl

Propagate implicitly added attributes/arguments to instantiated rules

---

examples/hellogrpc/py/requirements.txt
examples/hellogrpc/py/server/BUILD

* All current Travis CI would fail because hellogrpc/py e2e test would
fail. This PR fix this test, so that Travis CI works again.
* hellogprc/py server would produce a py_image which is failed to
start because of missing a dependency:
``` bash
Traceback (most recent call last):
File "/app/hello_grpc/py/server/server.binary.runfiles/__main__/hello_grpc/py/server/server.py", line 1, in <module>
import grpc
File "/app/hello_grpc/py/server/server.binary.runfiles/pypi__grpcio_1_6_0/grpc/__init__.py", line 22, in <module>
from grpc._cython import cygrpc as _cygrpc
File "src/python/grpcio/grpc/_cython/cygrpc.pyx", line 17, in init grpc._cython.cygrpc (src/python/grpcio/grpc/_cython/cygrpc.c:29041)
```
* Adding setuptools in requirements fixes the problem.

fix hellogrpc/py examples by adding dependency

---

OWNERS

/assign @erain 
After this `/approve` should work as expected.
Do we want to enable blunderbuss to have prow automatically assign a reviewer on new PRs?

Create root-level OWNERS file

---

.gitignore
examples/hellogrpc/e2e-test.sh
examples/hellohttp/BUILD
examples/hellohttp/e2e-test.sh
examples/hellohttp/service.yaml
test-e2e.sh

/assign @erain 
* Check in the `hellohttp` service
* Update The `hellohttp`, `hellogrpc` test scripts to
- accept a list of languages (rather than just one)
- ensure the service exists
- print out all the app's resources before deletion
* Create a top-level `test-e2e.sh` that runs all the e2e tests
- essentially a clone of `.travis.yml`
- will be used by prow

Create a test-e2e.sh script which prow can run

---

examples/hellogrpc/cc/server/edit.sh
examples/hellogrpc/e2e-test.sh
examples/hellogrpc/go/server/edit.sh
examples/hellogrpc/java/server/edit.sh
examples/hellogrpc/py/server/edit.sh
examples/hellohttp/e2e-test.sh
examples/hellohttp/go/edit.sh
examples/hellohttp/java/edit.sh
examples/hellohttp/nodejs/edit.sh
examples/hellohttp/py/edit.sh
examples/todocontroller/e2e-test.sh
examples/todocontroller/py/edit.sh
k8s/apply.sh.tpl
k8s/create.sh.tpl
k8s/delete.sh.tpl
k8s/describe.sh.tpl
k8s/replace.sh.tpl
k8s/resolve-all.sh.tpl
k8s/resolve.sh.tpl
k8s/reverse.sh.tpl
test-e2e.sh

There are still systems widely in use where bash does not exist at `/bin/bash` (e.g. NixOS), or where `/bin/bash` is an extremely outdated version of bash (MacOS).  Using `/usr/bin/env` to locate bash increases portability.  It's not hermetic, but `/bin/bash` was already not hermetic.

Use /usr/bin/env bash for more portable shebang lines

---

WORKSPACE

Change to bazel 0.17.0rc1 broke this repo transitively via rules_docker

update docker rules pin again

---

images/gcloud-bazel/Makefile

Allows `PROJECT=my-project make push` in case someone wants to push this image to their own project

Allow project override

---

examples/hellogrpc/e2e-test.sh
examples/hellohttp/e2e-test.sh
examples/todocontroller/e2e-test.sh
k8s/describe.sh.tpl

If we do not include the `-o name` then the command output includes a ` (dry run)` suffix.
/assign @smukherj1 @nlopezgi 
This seems to be causing issues in recent kubectl versions (https://github.com/bazelbuild/rules_k8s/pull/193#issuecomment-431026365).
* Formatting fixes while I'm in these files
* Run `delete || true` before running create, in case zombie resources exist from a prior run.
* Logging the steps before they run to assist debugging

Use kubectl describe foo name

---

.bazelci/presubmit.yml
WORKSPACE
images/gcloud-bazel/BUILD.bazel
images/gcloud-bazel/Dockerfile
images/gcloud-bazel/sources.list
test-e2e.sh

For now only added logic to create the container. I haven't uploaded it to GCR because I don't have permissions to access gcr.io/rules-k8s.
The container built by this logic doesn't fully work because gcloud installation has some post processing steps after the extraction of the downloaded tarball. I tried to use bootstrap_image_macro from base_images_docker but ran into some issues. I commented out the call and I explain my issue in comments above the invocation of bootstrap_image_macro. The installation cleanup commands in bootstrap_image_macro show what's needed to fully install gcloud and kubectl in this container.
If this container looks acceptable, the next steps will be to upload this container to GCR and change the prow job definition to use this container. At the same time, the …

Add logic to generate bazel + gcloud container using rules_docker

---

examples/todocontroller/BUILD
examples/todocontroller/py/BUILD
k8s/object.bzl

This replaces #165 adds some examples as @fejta requested. The build would fail on master but is working on this branch.
Let me know if that is sufficient enough.

Propagate arguments for implicit attributes to instantiated rules

---

test-e2e.sh

The controller e2e test is being a bit buggy.  Disabling it until we work out the flakes.  This e2e test is currently blocking the test queue.

Disabling controller e2e test till it is less flakey

---

toolchains/kubectl/BUILD

Currently, the toolchains defined for kubectl place a constraint on both the target and execution platform. This results in a toolchain resolution failure when both platforms are different, _e.g.,_ by setting the Bazel `--platform` flag.
This PR removes the execution platform constraint from the kubectl toolchain, which is acceptable as the generated binaries are only expected to run on the target platform.
Fixes #215

Remove kubectl toolchain execution platform constraint

---

images/gcloud-bazel/Makefile

Use gcloud builds, and :latest-$USER

---

README.md
examples/hellohttp/e2e-test.sh
examples/hellohttp/java/BUILD
k8s/apply.sh.tpl
k8s/create.sh.tpl
k8s/delete.sh.tpl
k8s/describe.sh.tpl
k8s/object.bzl
k8s/replace.sh.tpl
toolchains/kubectl/BUILD

Trying this PR to replace all other PRs discussed in https://github.com/bazelbuild/rules_k8s/issues/209.
With this PR:
- users can add args (string list) to their k8s_deploy object
- users can use bazel run <target> -- <extra args>
- modified templates so the kubectl command is printed out when running bazel run <target>, useful for validation in e2e tests
Hope this satisfies everyone's needs.
fyi @chrislovecnm @Globegitter @omadawn

Arbitrary args for kubectl

---

README.md
toolchains/kubectl/README.md

Documenting the kubectl toolchain rule usage.

Kubectl via toolchains (documentation)

---

WORKSPACE
examples/hellogrpc/cc/client/BUILD
examples/hellogrpc/cc/server/BUILD
examples/hellogrpc/e2e-test.sh
examples/hellogrpc/go/client/BUILD
examples/hellogrpc/go/server/BUILD
examples/hellogrpc/go/server/main.go
examples/hellogrpc/java/client/BUILD
examples/hellogrpc/java/server/BUILD
examples/hellogrpc/proto/BUILD
examples/hellogrpc/py/client/BUILD
examples/hellogrpc/py/requirements.txt
examples/hellogrpc/py/server/BUILD
examples/hellogrpc/py/server/server.py

* Remove pubref/rules_protobuf
* Add stackb/rules_proto
* Update rules_go to 0.16.0

Update protobuf rules for examples

---

README.md
WORKSPACE
k8s/k8s.bzl
k8s/object.bzl
toolchains/kubectl/README.md
toolchains/kubectl/kubectl_configure.bzl
toolchains/kubectl/kubectl_toolchain.bzl

* also make default (when importing these rules) to use kubectl from path (simpler atm, less error prone)
* provide instructions for how to use the new option to build kubectl from sources
* also show a nice error message if no kubectl tool is found when user attempts to do `bazel run` for a target that requires the toolchain is configured
https://github.com/bazelbuild/rules_k8s/issues/234

Update toolchain docs

---

.bazelci/presubmit.yml
WORKSPACE

fixes https://github.com/bazelbuild/rules_k8s/issues/240
I found hard to fix issue since this repo depends on https://github.com/stackb/rules_proto which depends (https://github.com/stackb/rules_proto/blob/master/deps.bzl#L158) on https://github.com/grpc/grpc which depends (https://github.com/grpc/grpc/blob/d6c989936c0d6fdaf481e4ac460beaebc6c57f20/bazel/grpc_deps.bzl#L116) on https://github.com/protocolbuffers

update pin to rules_proto

---

WORKSPACE

fixes https://github.com/bazelbuild/rules_k8s/issues/240

use latest release of protobuf

---

WORKSPACE
k8s/k8s.bzl
toolchains/kubectl/README.md
toolchains/kubectl/defaults.bzl
toolchains/kubectl/kubectl_configure.bzl

Documentation & refactoring for custom kubectl from source

---

toolchains/kubectl/README.md
toolchains/kubectl/kubectl_configure.bzl
toolchains/kubectl/kubectl_toolchain.bzl

Addresses customer request to download v1.10.0 in #245 because
v1.10.0 can't be built from source. This fixes #245

Allow downloading prebuilt binary in kubectl toolchain

---

.bazelci/presubmit.yml

Fixes https://github.com/bazelbuild/rules_k8s/issues/255
Bazel CI no longer has docker installed (it actually runs inside docker and they'd rather not have to setup sibling docker). Lets see if just removing some targets is enough to get this passing. We can probable get those targets running on BazelCi+RBE that does have docker

remove targets that cant run on Bazel CI

---

.bazelci/presubmit.yml
k8s/object.bzl
k8s/objects.bzl
test-e2e.sh
toolchains/kubectl/kubectl_configure.bzl

Disabled buildifier in buildkite and enabled it in e2e tests with
specific warnings disabled.

Fix buildifier 0.22.0 lint warnings

---

WORKSPACE

Fixes --incompatible_bzl_disallow_load_after_statement tracked in #248

Explicitly import latest version of grpc

---

README.md

The current documentation yields an error.

[DOCS] update the load command for container_repositories

---

README.md
examples/hellogrpc/BUILD
examples/hellogrpc/service.yaml
k8s/object.bzl

The new "substitutions" parameter is passed to a call to
actions.expand_template on the template (json or yaml) that is passed
into k8s_object.
Fixes: #244

Add a "substitutions" parameter to operations

---

README.md
examples/hellogrpc/BUILD
examples/hellogrpc/e2e-test.sh
k8s/apply.sh.tpl
k8s/create.sh.tpl
k8s/object.bzl

Add support for passing in a generated kubeconfig file to `rules_k8s`
objects. This can be used to pass in a configuration that's generated by
Bazel.

rules_k8s: Support passing in a kubeconfig file

---

WORKSPACE

This moves the explicit rules_python dep up in the WORKSPACE file so it takes precedence. It also adds an explicit dep on subpar to override transitive deps on it that have yet to be updated.

Update deps for --incompatible_remove_old_python_version_api

---

README.md

Unless I'm misunderstanding the meaning of required here? Let me know what you think!

images is not required on k8s_object

---

k8s/object.bzl
k8s/objects.bzl

This addresses the incompatible change via the `--incompatible_disallow_struct_provider_syntax` flag described [here](https://github.com/bazelbuild/bazel/issues/7347).

Return providers instead of struct from rule impl functions

---

WORKSPACE

With this commit, rules_k8s works with `--incompatible_depset_union`.
#248

Update jsonnet dependency

---

examples/hellogrpc/e2e-test.sh
k8s/delete.sh.tpl
k8s/with-defaults.bzl

It is now possible to use `kubeconfig` in `k8s_defaults`, which we use with k3s internally.
In `.delete` rules, `kubeconfig` was ignored, so fix that.

Allow kubeconfig in k8s_defaults and .delete rules

---

toolchains/kubectl/README.md

The docs do not give the correct path.  They give the path inside our
repo, not the path you need to use in your workspace file.

Fixing kubectl toolchain docs

---

examples/BUILD
examples/e2e_gc.py
test-e2e.sh

Best effort deletion of kubernetes namespaces created by e2e test runs
more than an hour old.

Add a namespace garbage collector.

---

.bazelrc
WORKSPACE
k8s/BUILD

context: https://github.com/bazelbuild/rules_k8s/issues/305
Creating PR to discuss issues related to 0.25.0rc1 with stakeholders.
Note this will fail until Bazel 0.25.0 is out

using python_version to try issues with 0.25.0rc1

---

README.md
examples/hellogrpc/BUILD
k8s/objects.bzl

We are making use of `--define` flags to deploy targets into different environments. Right now we are making use of an `alias` to achieve this but it has limitations and adds code complexity that we would like to remove. Unfortunately macros can not manipulate `select` statements directly so I have to treat a `dict` as a special case. See https://github.com/bazelbuild/bazel/issues/8419

Add support for select statement for k8s_objects.

---

WORKSPACE

With this change, the repository can build with Bazel flag
--incompatible_depset_is_not_iterable, which will be enabled by default
soon.

Update dependency on grpc

---

toolchains/kubectl/kubectl_configure.bzl

The kubernetes repo expects io_kubernetes_build to be called io_k8s_repo_infra.
If that repository is not available the build will fail with the following error message.
"error loading package '@io_kubernetes//staging/src/k8s.io/apimachinery/pkg/util/sets': Unable to find package for @io_k8s_repo_infra//defs:go.bzl: The repository '@io_k8s_repo_infra' could not be resolved."
Related change:
https://github.com/kubernetes/kubernetes/commit/e216995ef15a0e2a64f7742e5d5b7965170e4dcf
Fixes #358 
This likely breaks backward compatibility with kubernetes < 1.14
Is there any good way to parse versions in skylark?

fix: building kubectl v1.14.3 fails with missing dependency

---

WORKSPACE

Renovate bot fails to update the protobuf dependency (#356) as it's unable to guess the new `strip_prefix` value.

Update protobuf pin

---

WORKSPACE
images/gcloud-bazel/BUILD

* remove reference to base_images_docker
* updated rules_docker pin (this PR superseds https://github.com/bazelbuild/rules_k8s/pull/391 that is failing as it includes an update to rules_docker and indirect update to grpc)
* Moved grpc load higher up in WORKSPACE as grpc pin in rules_docker is failing with rules_k8s.
* Had to move rules_go further up otherwise grpc cannot be properly loaded
* grpc cannot be updated (https://github.com/bazelbuild/rules_k8s/pull/384) as rules_proto we are using are broken with latest version of grpc
* Created issue in rules_proto to fix: https://github.com/stackb/rules_proto/issues/108

remove base_images_docker and update rules_docker

---

WORKSPACE

Addresses [renaming canonical workspace issue](https://github.com/bazelbuild/rules_python/issues/203).

Fix rules_python workspace name

---

examples/imagestamping/BUILD
examples/imagestamping/deployment.yaml
examples/imagestamping/go/BUILD
examples/imagestamping/go/main.go
examples/imagestamping/stamp_variables
k8s/object.bzl
k8s/resolver.py
k8s/resolver_test.py

This addresses issue #378 
Adds support for using stamp variables for the repository tag so that it will resolve the repository name and tag prior to pushing the container to the repository. It now works similar to the docker_rules `push_container` rule.
```python
k8s_object(
name = "image-stamping",
template = ":deployment.yaml",
images = {
"index.docker.io/parsec86/{REPOSITORY}:{STABLE_GIT_COMMIT}": "//examples/imagestamping/go:go-container",
}
)
```
>**Note** - Stamping only effects the resolved image name that is pushed to the container registry. The container digest will still be used inside your resolved template since the digest is immutable.

feat: support stamping repository tags for images

---

k8s/object.bzl

https://docs.bazel.build/versions/master/skylark/performance.html#use-ctxactionsargs-for-command-lines
Reduce usage of to_list in depsets and use ctx.actions.args instead of args list

performance improvements for rules_k8s

---

k8s/object.bzl

depset transitive expects sequence of depsets

---

k8s/go/cmd/resolver/resolver.go
k8s/go/cmd/resolver/resolver_test.go

Support resolving YAML streams in Go resolver

---

k8s/go/cmd/resolver/resolver.go

This is how the python resolver behaves. Tested with
bazel run //prow/cluster/monitoring:prometheus_operator on
kubernetes/test-infra

Go resolver should return strings as is on any kind of error

---

k8s/BUILD
k8s/k8s.bzl
k8s/reverser.py

* Upgrade PyYAML to 5.1.2
* Select the PY2 or PY3 version of PyYAML depending on the desired PY version
I've been testing this downstream, and have confirmed that rules such as `.delete` works with both `--host_force_python=PY3` and `--host_force_python=PY2`.

Make //k8s:reverser and //k8s:stamper PY2 and PY3 compatible

---

WORKSPACE

See https://github.com/bazelbuild/bazel/issues/6799 for more information about `maven_jar`'s removal, and [this document](https://docs.google.com/document/d/1CqxPv-TwvFWBHgtg7_QhVfck4vH4rnmCU_IuMdC7O2M/edit#) for the design behind the migration tool used for this PR.

Migrate maven_jar usage to maven_install. maven_jar will be removed from Bazel 2.0.

---

README.md

This is no longer necessary since the resolver was migrated (released in 0.3.0), and #461 (not yet released).

Remove PY2 notice from the README

---

k8s/go/cmd/resolver/resolver.go

I spent a while troubleshooting an issue based on an error message that didn't show the underlying cause.  I thought variables were not being substituted correctly but instead it was something unrelated.
Error message prior to the change:
```
2020/01/02 13:08:17 Unable to publish images: unable to publish image docker-registry/docker-repo:{STABLE_GIT_COMMIT}
```
Error message after the change:
```
2020/01/02 13:08:17 Unable to publish images: unable to push image docker-registry/docker-repo:323fde312207a0b5d67c7a0326833a94dd54e0bd: TAG_INVALID: The image tag '323fde312207a0b5d67c7a0326833a94dd54e0bd' already exists in the 'docker-repo' repository and cannot be overwritten because the repository is immutable.
```
I'm not sure if this is the best way to propagate the error but it clears up …

propagate error message up the stack

---

WORKSPACE
examples/hellogrpc/java/client/HelloClient.java
examples/yarn.lock
k8s/k8s.bzl
third_party/build_stack_rules_proto/stackb.patch

To make sure we pull everything from maven central using https.
Replaces:
https://github.com/bazelbuild/rules_k8s/pull/506
https://github.com/bazelbuild/rules_k8s/pull/509
https://github.com/bazelbuild/rules_k8s/pull/507

update rules_docker & other deps

---

README.md

I run the bazel with `--workspace_status_command` to stamp the values such as GCP project id, GCR repository name, GKE cluster name and so on, and I passed the path to the shellscript as written on README.
However it got error saying "command not found"
```
$ bazel run //:gke_deploy --verbose_failures
INFO: Analyzed target //:gke_deploy (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: Process exited with status 127
/bin/sh: variables.sh: command not found
Target //:gke_deploy failed to build
INFO: Elapsed time: 0.381s, Critical Path: 0.06s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
$ cat .bazerlrc
run --workspace_status_command=./variables.sh
```
I found the exact discussion around this on …

Fix the documentation bug on stamping

---

README.md

The current latest is v0.4 whereas README still uses v0.3.1. Even thought it is an example snippet, it's more developer friendly to provide the copy-n-paste-able snippet. In that sense, changed the version used in the snippet.
I checked up the hash on my local machine but if the value is incorrect, I would like to have the correct value on the review time.
```
$ openssl sha256 rules_k8s-v0.4.tar.gz
SHA256(rules_k8s-v0.4.tar.gz)= d91aeb17bbc619e649f8d32b65d9a8327e5404f451be196990e13f5b7e2d17bb
```

Fix version used in README to v0.4 (current latest)

---

README.md

Small fix but changed the doc to be explicit on the unavailable options when `kind` or `cluster` are omitted.

Modify description of k8s_object to be more explicit

---

README.md

In #161 and #162, the attribution `resolver_args` was added to `k8s_object`, but the attribute was not documented. As described in the doc, some options such as `--allow_unused_images` should be passed via this option.

Add descriptions on `resolver_args`

---

images/gcloud-bazel/Dockerfile
images/gcloud-bazel/Makefile
images/gcloud-bazel/cloudbuild.yaml

This will allow CI to choose between those two versions via a .bazelversion file

Install an old version of bazel in gcloud-bazel.

---

CODEOWNERS
OWNERS

No need to define reviewers when it is the same as approvers.
/assign @michelle192837 @chases2

Keep approvers/reviewers up to date.

---

examples/hellogrpc/e2e-test.sh
examples/hellohttp/e2e-test.sh
k8s/object.bzl
k8s/objects.bzl

When automating interactions with the outputs of a k8s_object, it's easy to find and operate on tasks like ".apply" because there is a sigil (literally, ".apply") that you can search for in the target output. Because there is no corresponding sigil for the "resolve" target it's difficult to filter for this task.
Looking for the absence of "apply", "delete", etc is not very future-proof, since other target types could be introduced. Filtering out targets that contain a period between the colon and the newline is restrictive on target names.
I believe this is would achieve the desired effect.

Add a ".resolve" alias for the resolve task

---

k8s/object.bzl

PR to address https://github.com/bazelbuild/rules_k8s/issues/536
Retain the current behaviour of depending on volatile-status.txt and stable-status.txt, but allow a user to override the stamp inputs.

Allow overriding the stamp inputs

---

README.md
examples/hellogrpc/e2e-test.sh
examples/hellohttp/e2e-test.sh
k8s/BUILD
k8s/diff.sh.tpl
k8s/go/cmd/resolver/resolver.go
k8s/object.bzl
k8s/objects.bzl

Previously #410
This adds a `.diff` target to `k8s_object`. In order to avoid pushing when resolving for the purposes of the diff, this also adds a no_push flag to the resolver.
Fixes #242

Add .diff target

---

toolchains/kubectl/BUILD

Closes https://github.com/bazelbuild/rules_k8s/issues/530.
This allows defining your own kubectl toolchains; e.g.
```
toolchain(
name = "my_kubectl_toolchain",
target_compatible_with = ...,
toolchain = "//my/local:kubectl",
toolchain_type = "@io_bazel_rules_k8s//toolchains/kubectl:toolchain_type",
)
```
```
...
load("@io_bazel_rules_k8s//k8s:k8s.bzl", "k8s_repositories")
k8s_repositories()
load("@io_bazel_rules_k8s//k8s:k8s_go_deps.bzl", k8s_go_deps = "deps")
k8s_go_deps()
register_toolchains(
"//:my_kubectl_toolchain",
)
```
which then allows more flexibility over what `kubectl_configure` currently allows.

Make the kubectl toolchain type public

---

BUILD
WORKSPACE
k8s/go/cmd/resolver/BUILD

Executing `bazel run //:gazelle` on master breaks the build due to changes introduced by `go_naming_convention` and due to the fact that the name of the `io_bazel_rules_docker` repository rule does not match what gazelle would generate based on the importpath. This PR should allow someone to run gazelle on this repository with breaking things.

fix gazelle

---

k8s/apply.sh.tpl
k8s/create.sh.tpl
k8s/delete.sh.tpl
k8s/describe.sh.tpl
k8s/diff.sh.tpl
k8s/replace.sh.tpl
k8s/resolve-all.sh.tpl
k8s/resolve.sh.tpl

The current logic for finding the runfiles directory only works when the
targets created by rules_k8s are invoked directly. Creating a
sh_binary() that chains multiple commands together doesn't work, as the
placement of the script relative to the runfiles directory will be
different.
This issue also affected rules_docker at some point in the past. This
change basically imports the new guess_runfiles() logic that
rules_docker uses.

Allow rules_k8s targets to be invoked within other Bazel targets

---

.bazelci/presubmit.yml

Recent versions of pyyaml do not support ubuntu 16 (which has past its lifetime support window)

Drop support for ubuntu 16

---

k8s/objects.bzl

Fixes: https://github.com/bazelbuild/rules_k8s/issues/679
This diff proposes one strategy we could take to wrapping the command execution of the kubectl diffs in order to address the above issue.

Enable wrapping k8s_objects diff exit codes

---

k8s/k8s.bzl
toolchains/kubectl/BUILD

1. Added and registered `kubectl_macos_arm64_toolchain`
2. Changed the name of `kubectl_osx_toolchain` to `kubectl_macos_x86_64_toolchain` and added an alias for backwards compatibility. Also updated the registration.
3. Made `toolchain/kubectl` package `public` to allow for extensions for this toolchain_type
#696

Added toolchain support for Apple M1 and made toolchain_type public to allow extensions

---

WORKSPACE
k8s/k8s.bzl
k8s/k8s_go_deps.bzl

This PR takes care of a bunch of subtasks of #672
And also closes #587, #632, #645
Dependencies updated are:
* Bazel (in .bazelversion)
* protobuf (in WORKSPACE)
* rules_python (in WORKSPACE)
* grpc (in WORKSPACE)
* rules_jsonnet (in WORKSPACE)
* PyYaml (in k8s/k8s.bzl and requirements.txt)
* rules_go (in k8s/k8s.bzl)
* gazelle (in k8s/k8s.bzl)
* skylib (in k8s/k8s.bzl)
* go-cmp (in k8s/k8s_go_deps.bzl)
* Go compiler version (in k8s/k8s_go_deps.bzl)

Update multiple dependency versions.
