.ci/rules_k8s.json

Fixes https://github.com/bazelbuild/rules_k8s/issues/6

Add a Bazel CI Config for rules_k8s.

---

.travis.yml
WORKSPACE
examples/hello-grpc/cc/client/BUILD
examples/hello-grpc/e2e-test.sh
examples/hello-grpc/java/client/BUILD
examples/hello-grpc/java/client/HelloClient.java
examples/hello-grpc/java/server/BUILD
examples/hello-grpc/java/server/HelloServer.java
examples/hello-grpc/java/server/edit.sh
examples/hello-grpc/proto/BUILD
examples/hello-grpc/proto/simple.proto

Currently this is based on the actions change, I'll ping this once that is merged and I've rebased.

Java sample

---

README.md
WORKSPACE
examples/hello-grpc/cc/client/main.cc
examples/hello-grpc/e2e-test.sh
examples/hello-grpc/go/client/main.go
examples/hello-grpc/java/client/HelloClient.java
k8s/BUILD
k8s/create.sh.tpl
k8s/object.bzl
k8s/stamper.py

Fixes https://github.com/bazelbuild/rules_k8s/issues/10

Add support for stamping cluster and namespace

---

WORKSPACE
examples/hellogrpc/py/client/BUILD
examples/hellogrpc/py/server/BUILD

This pickes up the s/package/requirement/ change.

Update the rules_python dependency.

---

WORKSPACE
examples/BUILD
examples/container.libsonnet
examples/deployment.libsonnet
examples/hellogrpc/BUILD
examples/hellogrpc/deployment.jsonnet
examples/hellogrpc/deployment_test.py
examples/hellogrpc/go/server/BUILD
examples/hellogrpc/java/server/BUILD
examples/hellohttp/BUILD
examples/hellohttp/deployment.jsonnet
examples/hellohttp/deployment_test.py

Fixes: https://github.com/bazelbuild/rules_k8s/issues/4

This adds a very simple example of templating using rules_jsonnet.

---

WORKSPACE

Originally: https://github.com/bazelbuild/rules_k8s/pull/39 from @pcj

Update rules_protobuf to v0.8.1 (depset fixes for bazel 0.6.0)

---

WORKSPACE
examples/hellogrpc/cc/server/BUILD
examples/hellogrpc/go/server/BUILD
examples/hellogrpc/java/server/BUILD
examples/hellogrpc/py/server/BUILD
examples/hellohttp/go/BUILD
examples/hellohttp/java/BUILD
k8s/object.bzl

... which restructures the repository a bit.

Upgrade to the latest version of rules_docker

---

README.md
examples/hellohttp/e2e-test.sh
k8s/BUILD
k8s/apply.sh.tpl
k8s/object.bzl

Fixes: https://github.com/bazelbuild/rules_k8s/issues/43

Add an apply action.

---

README.md

Fixes: https://github.com/bazelbuild/rules_k8s/issues/52

Document how to use --workspace_status_command per-repo.

---

examples/todocontroller/py/controller.py

This updates the example to follow the pattern discussed [here])https://github.com/kubernetes-incubator/client-python/issues/334).

Controllers following the pattern currently used are unstable.

---

.ci/rules_k8s.json
WORKSPACE

Fixes: https://github.com/bazelbuild/rules_k8s/issues/59

Re-enable OSX testing.

---

k8s/objects.bzl

Otherwise all the targets in the objects are rebuild.

Use the same configuration as in objects.bzl

---

k8s/objects.bzl

Merge https://github.com/bazelbuild/rules_k8s/pull/79 into master

Fix config

---

k8s/objects.bzl

Objects visibility

---

README.md
k8s/object.bzl

* Make resolver a public property
* Review comments

Make resolver a public property (#95)

---

k8s/object.bzl

The `+` operator on dicts is deprecated and will be removed.

Remove usages of `+` on dicts

---

k8s/object.bzl

* implemented make vars expansion
* added make vars expansion for namespace and image_chroot

Expand make vars for cluster name (#106)

---

k8s/objects.bzl

Fixes: https://github.com/bazelbuild/rules_k8s/issues/97

Delete objects in reverse order.

---

WORKSPACE
examples/todocontroller/BUILD
examples/todocontroller/e2e-test.sh
examples/todocontroller/joined.yaml
k8s/BUILD
k8s/object.bzl
k8s/reverse.sh.tpl
k8s/reverser.py

Fixes: https://github.com/bazelbuild/rules_k8s/issues/109

This splits and reverses a multi-document yaml for k8s_object delete.

---

k8s/delete.sh.tpl

Fixes: https://github.com/bazelbuild/rules_k8s/issues/111

Ignore not-found on deletions.

---

README.md

/assign @erain @nlopezgi 
Preview: https://github.com/fejta/rules_k8s/blob/doc/README.md#support

Add support options to README.md

---

k8s/object.bzl

Unlock extra actions if "context" attribute is set

---

.bazelrc
WORKSPACE
examples/hellogrpc/e2e-test.sh
examples/hellohttp/e2e-test.sh
examples/todocontroller/e2e-test.sh
print-workspace-status.sh
test-e2e.sh

This attempts to fix issue #173 
Don't review just yet. Want to see if the CI jobs pass

Use build id and repo name in namespace to uniquify

---

k8s/object.bzl

Just run buildifier on object.bzl so that my other pr (https://github.com/bazelbuild/rules_k8s/pull/229/files) is not a mess

buildifier for objects.bzl

---

README.md
WORKSPACE
k8s/k8s.bzl
k8s/object.bzl
toolchains/kubectl/README.md
toolchains/kubectl/kubectl_configure.bzl
toolchains/kubectl/kubectl_toolchain.bzl

ugh, sent the previous pull request to the wrong branch. Apologies

Update toolchain docs

---

.bazelci/presubmit.yml

Mac is having issues pulling the base images, lets reduce the number of things we test on mac, sadly, our mac features might drift.

test only a few things on mac, its flaky

---

WORKSPACE
examples/hellogrpc/e2e-test.sh
examples/hellohttp/BUILD
examples/hellohttp/deployment.jsonnet
examples/hellohttp/deployment.yaml
examples/hellohttp/e2e-test.sh
examples/hellohttp/go/BUILD
examples/hellohttp/java/BUILD
examples/hellohttp/nodejs/BUILD
examples/hellohttp/py/BUILD
examples/todocontroller/e2e-test.sh
examples/util.sh
test-e2e-local.sh
test-e2e.sh

code changes to enable running e2e tests locally

Local e2e tests

---

WORKSPACE

https://github.com/bazelbuild/rules_k8s/pull/257 didn't fix the problem, this one does.

Update rules_proto (second try)

---

.gitignore
WORKSPACE
k8s/object.bzl

Also updated a few repositories to pull in fixes to other incompatible
changes that haven't been enabled by default in Bazel yet. More work is
needed in rules_grpc and com_google_protobuf. See #248

Fix --incompatible_disallow_dict_plus

---

WORKSPACE

Fixes --incompatible_disable_legacy_cc_provider issues which fixes #272

Update rules_go to 0.17.0

---

WORKSPACE
k8s/object.bzl
k8s/objects.bzl
third_party/com_github_grpc_grpc/bcc9f308c6.patch

Includes patch for gRPC upstream until they fix issue.

Fix incompatible issue

---

WORKSPACE

Fixes incompatible_disable_deprecated_attr_params

update protobuf pin

---

.bazelci/presubmit.yml
WORKSPACE
k8s/k8s.bzl

Update go to 0.18.2 & disable go targets on Ubuntu 14.04

---

.bazelci/presubmit.yml
WORKSPACE
k8s/k8s.bzl

Update rules_jsonnet pin

---

k8s/k8s.bzl

fixes https://github.com/bazelbuild/rules_k8s/issues/322

pull rules_go uniformly in k8s.bzl vs WORKSPACE

---

.bazelrc
README.md
examples/hellogrpc/cc/server/BUILD
k8s/object.bzl

This is a need that arose internally. Let me know if you need any more information / backcground on the changes.

Add make resolve support for images.

---

WORKSPACE
examples/hellohttp/static-deployment.yaml
examples/imagestamping/BUILD
k8s/go/cmd/resolver/BUILD
k8s/go/cmd/resolver/resolver.go
k8s/go/cmd/resolver/resolver_test.go
k8s/k8s.bzl
k8s/k8s_go_deps.bzl
k8s/object.bzl

Attempt to flip the default resolver to use Go but keep the ability to switch to the python resolver for now.

Complete the implementation of the Go resolver

---

k8s/k8s.bzl

Update bazel_skylib + rules_go

---

examples/hellogrpc/proto/BUILD
k8s/k8s.bzl

Update rules_go version along with grpc dependencies fix

---

examples/hellogrpc/proto/BUILD

Make rules_k8s compatible with --incompatible_load_proto_rules_from_bzl

---

k8s/reverser.py

Fix error "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12345: ordinal not in range(128)"

fix encoding error

---

WORKSPACE
k8s/k8s.bzl

Update io_bazel_rules_go pin

---

images/gcloud-bazel/Dockerfile
images/gcloud-bazel/cloudbuild.yaml

* Can add one tag per docker tag call
* Dockerfile uses  not
ref https://github.com/bazelbuild/rules_k8s/pull/549

Correct typos:

---

k8s/object.bzl

Use substituted file instead of plain template for "reversed" k8s object, thus enabling its correct handling for ".delete" targets.
Fixes: #562 #556

Use substituted template for delete action

---

k8s/k8s.bzl
toolchains/kubectl/BUILD
toolchains/kubectl/README.md

Add kubectl toolchain for linux arm64

---

README.md

We're big adopters of `rules_k8s` at Cookies :)

Add Cookies to Adopters list

---

toolchains/kubectl/BUILD

Do not use constraints from bazel_tools
